In [ ]:
from tensorflow import keras 
import numpy as np

In [ ]:
x =np.array([0,1,2,3,4,5],dtype='float64')
y=x*2+1
print(y)

[ 1.  3.  5.  7.  9. 11.]


In [ ]:
model = keras.models.Sequential()
#1차원 데이터 아웃풋, inputshape이 1개만 들어온다 
model.add(keras.layers.Dense(1,input_shape=(1,)))
model.compile('Adadelta','mse')

In [ ]:
model.fit(x,y,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 12ms/step - loss: 64.0940
Epoch 2/1000
1/1 [==============================] - 0s 8ms/step - loss: 64.0939
Epoch 3/1000
1/1 [==============================] - 0s 9ms/step - loss: 64.0938
Epoch 4/1000
1/1 [==============================] - 0s 10ms/step - loss: 64.0937
Epoch 5/1000
1/1 [==============================] - 0s 11ms/step - loss: 64.0936
Epoch 6/1000
1/1 [==============================] - 0s 11ms/step - loss: 64.0935
Epoch 7/1000
1/1 [==============================] - 0s 7ms/step - loss: 64.0934
Epoch 8/1000
1/1 [==============================] - 0s 19ms/step - loss: 64.0933
Epoch 9/1000
1/1 [==============================] - 0s 11ms/step - loss: 64.0932
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 64.0931
Epoch 11/1000
1/1 [==============================] - 0s 9ms/step - loss: 64.0930
Epoch 12/1000
1/1 [==============================] - 0s 5ms/step - loss: 64.0929
Epoch 13/1000
1/1 [============

In [ ]:
model.predict([7,10,99]) #with 'sgd' 100번 

1/1 [==============================] - 0s 98ms/step


array([[ 15.397007],
       [ 21.742079],
       [209.97919 ]], dtype=float32)

In [ ]:
model.predict([7,10,99]) #with 'sgd' 1000번 

1/1 [==============================] - 0s 32ms/step


array([[ 15.001059],
       [ 21.00198 ],
       [199.0293  ]], dtype=float32)

In [ ]:
model.predict([7,10,99]) #with 'Adadelta' 100번 

1/1 [==============================] - 0s 85ms/step


array([[ -2.5548398],
       [ -3.6498384],
       [-36.1348   ]], dtype=float32)

In [ ]:
model.predict([7,10,99]) #with 'Adadelta' 1000번

1/1 [==============================] - 0s 33ms/step


array([[ -2.536699 ],
       [ -3.6248949],
       [-35.90804  ]], dtype=float32)